development:
  adapter: postgresql
  encoding: unicode
  database: travellers_nomadic_hut_development
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: travellers_nomadic_hut_test
  pool: 5
  username: postgres
  password: password
